version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  test:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - node/install-packages<% if (yarn) { %>:
          pkg-manager: yarn<% } %>
      - run:
          name: Lint
          command: <%= yarn ? 'yarn' : 'npm run' %> lint
      - run:
          name: Run Tests
          command: <%= yarn ? 'yarn' : 'npm run' %> test

workflows:
  test:
    jobs:
      - test
